/**
 * Generates CLAUDE.md content based on the secrets the user has stored.
 * This file helps Claude Code understand how to use secrets without seeing values.
 */

export function generateClaudeMdContent(secretNames: string[]): string {
  const secretsTable = secretNames.length > 0
    ? secretNames.map(name => `| ${name} | User-defined | \`process.env.${name}\` |`).join('\n')
    : '| (No secrets added yet) | - | - |';

  return `# Scrt - Secret Access Reference

## How Secret Injection Works

Secrets are stored encrypted and injected at runtime as environment
variables via the \`scrt\` CLI. You NEVER see the actual values.

### Injection Mechanism

\`\`\`
+----------------+     +----------------+     +----------------+
| Your Command   | --> | scrt run ...   | --> | Command runs   |
| (no secrets)   |     | injects env vars |   | with secrets   |
+----------------+     +----------------+     +----------------+
\`\`\`

The secret value exists ONLY in the subprocess environment.
It is never written to disk or returned to the LLM.

---

## Stored Secrets

| Name | Purpose | Access Via |
|------|---------|------------|
${secretsTable}

---

## How to Run Commands with Secrets

Wrap your command with \`scrt run\`. Secrets are injected as standard
environment variables. Programs read them via \`process.env.KEY\` (Node),
\`os.environ['KEY']\` (Python), \`std::env::var("KEY")\` (Rust), etc.

### Examples

**Node.js script reading from env:**
\`\`\`bash
scrt run node deploy.js
# deploy.js uses: const key = process.env.PRIVATE_KEY
\`\`\`

**Python script:**
\`\`\`bash
scrt run python3 script.py
# script.py uses: key = os.environ['API_KEY']
\`\`\`

**Verify what's injected (safe — values only in subprocess):**
\`\`\`bash
scrt run env | grep PRIVATE_KEY
\`\`\`

**Selective injection:**
\`\`\`bash
scrt run --only API_KEY,DB_URL node server.js
\`\`\`

---

## Adding or Editing Secrets

Open the LLM Secrets app and use the Secrets tab to add or edit secrets.
After editing, regenerate this file from the Claude MD tab.

---

## What You Can See vs. What You Cannot

| You CAN See | You CANNOT See |
|-------------|----------------|
| Secret names (e.g., PRIVATE_KEY) | Secret values (e.g., 0x7f3a...) |
| Command structure | The actual injected value |
| Transaction hashes | Private keys |
| Success/failure messages | Passwords or tokens |

---

## Security Model

**Always true, regardless of settings:**

1. **LLM never sees secrets** - Values are never returned to Claude Code
2. **LLM can use secrets** - Wrap commands with \`scrt run\`, values injected at runtime
3. **Secrets exist only in subprocess** - Isolated from main process memory
4. **Touch ID required** - Master key stored in macOS Keychain

---

## Troubleshooting

### "Could not retrieve master key"
The Keychain item may require the LLM Secrets app to be set up.
Open the app and complete the setup wizard.

### "No encrypted .env file found"
No secrets have been saved yet. Open LLM Secrets and add secrets.

### "Command failed"
Check if the command syntax is correct. The secret injection happens
transparently - if the command fails, it's likely a command issue,
not a secret issue.

---

*Generated by Scrt Setup Wizard*
`;
}
